# golangci-lint configuration for CROP cryptographic library
# Focus on security, correctness, and maintainability

version: 2

run:
  timeout: 5m
  go: '1.25'
  tests: true

linters:
  enable:
    # Critical Security & Correctness
    - gosec           # Security-focused linter (critical for crypto code)
    - errcheck        # Ensures errors aren't ignored
    - govet           # Go's official checker for suspicious constructs
    - staticcheck     # Comprehensive bug/performance/style checker
    
    # Bug Prevention
    - ineffassign     # Detects ineffectual assignments
    - unused          # Finds unused code
    - nilnil          # Detects returning nil with nil errors
    - nilerr          # Finds code returning nil even on error
    - errchkjson      # Checks for unchecked errors in JSON encoding/decoding
    - bodyclose       # Ensures HTTP response bodies are closed
    - copyloopvar     # Detects loop variable capture issues (replaces exportloopref)
    
    # Code Quality & Maintainability
    - gocyclo         # Cyclomatic complexity
    - gocognit        # Cognitive complexity
    - dupl            # Code duplication detection
    - unconvert       # Unnecessary type conversions
    - unparam         # Unused function parameters
    - misspell        # Spelling mistakes

  disable:
    - godox           # TODOs are acceptable during development
    - testpackage     # Can be too restrictive

formatters:
  enable:
    - gofmt           # Standard Go formatting
    - goimports       # Auto-manages imports and formats

linters-settings:
  gosec:
    # G114: Use of net/http serve function that has no support for setting timeouts
    # G115: Integer overflow conversion
    # G404: Use of weak random number generator (crypto/rand)
    excludes:
      - G114  # HTTP servers not used in this library
      - G115  # Integer overflow conversions are safe in controlled contexts
    severity: high
  
  errcheck:
    # Check type assertions
    check-type-assertions: true
    # Check blank assignments
    check-blank: true
    # Ignore fmt.Print* functions
    exclude-functions:
      - (*github.com/mr-tron/base58.Encoder).Encode
  
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Struct field alignment is less critical
      - shadow          # Variable shadowing can be intentional
  
  staticcheck:
    checks: ["all"]
  
  gocyclo:
    min-complexity: 15  # Reasonable for crypto code
  
  gocognit:
    min-complexity: 30  # Allow moderate complexity (higher for tests)
  
  dupl:
    threshold: 100  # Minimum code duplication to report
  
  misspell:
    locale: US
  

  gocritic:
    disabled-checks:
      - unnamedResult     # Named returns can reduce clarity
      - hugeParam         # Sometimes necessary for crypto structs
      - singleCaseSwitch  # Single case switches with default are forward-compatible

issues:
  # Maximum issues count per linter
  max-issues-per-linter: 0
  # Maximum issues count overall
  max-same-issues: 0
  
  # Exclude specific issues or patterns
  exclude-rules:
    # Exclude test files from some checks
    - path: "_test\\.go"
      linters:
        - gosec
        - dupl
        - unparam
        - gocognit
        - gocyclo
        - errcheck
    
    # Single case switches are forward-compatible for future algorithm additions
    - linters:
        - gocritic
      text: "singleCaseSwitch"
    
    # Allow specific gofmt issues in test data
    - path: "_test\\.go"
      linters:
        - gofmt
